services:
  - type: web
    name: mlb-matchup-analyzer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install-deps
    startCommand: python startup.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.12
